#Comment to trigger commit

version: 2.1

parameters:

  # A parameter per package
  mvn_params:
    type: string
    default: "-Dacceptance.hds.rdbms.type=mysql -Dacceptance.hds.url=jdbc:mysql://localhost:3306 -Dacceptance.hds.dbuser=root -Dacceptance.hds.password=Pa55word"
  app:
    type: boolean
    default: true

executors:
  node:
    docker:
      - image: cimg/openjdk:15.0

jobs:
  conditional-job:
    executor: node
    steps:
      - when:
          condition:
            equal: [ "maven2", << pipeline.paramaters.mvn_params >> ]
          steps:
            - checkout:
                path: ~/project
            - run:
                name: Content
                command: |
                  echo $DISPLAY
                  mvn -B -f pom.xml clean install -V -U -Dacceptance.test.log.level=INFO -Dtycho.localArtifacts=ignore -Dsurefire.rerunFailingTestsCount=2 -Pacceptance,deployment-plugins << pipeline.parameters.mvn_params >> -s ctc.settings.xml


workflows:
  version: 2

  # Workflows defined for each package.

  api:
    when: << pipeline.parameters.api >>
    jobs:
      - conditional-job

  app:
    jobs:
      - conditional-job

